// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKVqLuYsNqqbVbrnHhius1otbapgSw8w',
    appId: '1:115879573652:android:b3ffbee1208fa6ea6d1c81',
    messagingSenderId: '115879573652',
    projectId: 'paynav-new',
    databaseURL: 'https://paynav-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paynav-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIXZ74Gi1cdGeNDFv53p6Nw2lDiL0C1Cw',
    appId: '1:115879573652:ios:1318df88374655786d1c81',
    messagingSenderId: '115879573652',
    projectId: 'paynav-new',
    databaseURL: 'https://paynav-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paynav-new.appspot.com',
    androidClientId: '115879573652-8okc7vqt6pd6ujopr2dqb85lvr29a57n.apps.googleusercontent.com',
    iosClientId: '115879573652-vvhpficid3715qccptbgtj1493i3npqb.apps.googleusercontent.com',
    iosBundleId: 'com.paynav.viaflutter.paynavForAll',
  );
}
